.\" $TOG: xkbevd.man /main/6 1998/02/12 09:34:24 kaleb $
.TH HOTKEYS 1 "15 March 2001" "0.5.2"
.SH NAME
hotkeys \- A hotkeys daemon for your Internet/multimedia keyboard in X
.SH SYNOPSIS
.B hotkeys \-t \fIkeyboard_type\fR
[\fIoptions...\fR]
.SH DESCRIPTION
.PP
This program sits at the back and listens for the hotkeys on your
keyboard. The buttons perform their intended behaviors, such as volume
up and down, mute the speaker, launch applications, etc.
The functions they perform are totally programmable.
.SH OPTIONS
.TP 8
.B \-h, \-\-help
Prints a usage message.
.TP 8
.B \-t, \-\-type=TYPE (mandatory)
Specify the keyboard type.
.TP 8
.B \-l, \-\-kbd\-list
Show all supported keyboards, and the code needed for the \-t option.
.TP 8
.B \-o, \-\-osd=STATE
Turn off or on the on-screen display, default is on if OSD support is
compiled with the program. Valid values for STATE are
off/0/no/on/1/yes.
.TP 8
.B \-L, \-\-loglevel=LEVEL
Set the log level in syslog. LEVEL is a value from 0 to 7. 7 will log
all messages.
.TP 8
.B \-d, \-\-cdrom\-dev=DEVICE
Specify the device of your CDROM drive, default to \fI/dev/cdrom\fR.
If you give 'none', CDROM related functions will all be disabled.
You probably need to define it if you are using devfs.
.TP 8
.B \-b, \-\-background
Tells \fIhotkeys\fP to fork itself (and run in the background).
.TP 8
.B \-F, \-\-fix\-vmware=TIME
This option is mainly for users who run both hotkeys and VMware at the
same time. Since VMware will delete some of the information from the
memory of the X keyboard configuration due to reasons that I don't
understand, a thread will be created to restore the necessary
information regularly. The default time interval is 10 seconds. You
can specify a time interval as you like, the value is in seconds. I
don't think this option will have any side-effect to the operation of
VMware, but if you find that this is not true, please file a bug
report. (This option is just a hack, I will implement a nicer method
to replace it.)
.\" .TP 8
.\" .B \-v
.\" Print more information, including debugging messages.   Multiple 
.\" specifications of \fI-v\fP cause more output, to a point.
.SH "SUPPORTED KEYBOARDS"
.\".TP 8
.IP 1. 5
.B Acer Airkey III Wireless keyboard
.\"The \fBvolume up\fR and \fBdown\fR works by changing the master volume of the
.\"mixer (\fI/dev/mixer\fR).
.\"
.\"The \fBmute\fR button sets the volume to 0 when pressed once, and restores the
.\"previous volume when pressed again.
.\"
.\"The \fBeject\fR button can eject and close the tray. The \fBplay\fR
.\"button can be used to close the tray too.
.IP 2. 5
.B Microsoft Internet, Internet Pro, and Natural Pro
.IP 3. 5
.B Memorex MX2500 and MX3000 keyboard
.IP 4. 5
.B SK-2500, SK-2501a, SK-2800c, SK-7100, SK-9925 USB (partial)
.IP 5. 5
.B Logitech cordless iTouch, Internet, Cordless Desktop keyboard
.IP 6. 5
.B Chicony KBP-8993
.IP 7. 5
.B Compaq KB-9963
.\" .PP
.\" For details please consult the file \fIkeyboard.list\fR.
.P
As I have only the Acer wireless keyboard, you can help
me to support other keyboards by sending me the list of keycodes of
the hotkeys on your keyboard. You can do this by using \fBxev\fR.
Contact me for the details.
.SH "KEYBOARD DEFINITION FILES"
Keycodes and the behavior of the hotkeys are stored in a \fBKeyboard
definition files\fR. Each supported keyboard has such a file placed in
either \fI/usr/local/share/hotkeys\fR or \fI/usr/share/hotkeys\fR,
depending on the installation configuration. For instance, the data
of the Acer Wireless keyboard is stored in the file \fIacerwl.def\fR.
Note that the part of the filename without the extension is the name
you give to the \fB\-t\fR option.
.P
Keyboard definition files are in XML format, which should be
self-explanatory.
.P
You can create your own definition file and placed it in
\fI$HOME/.hotkeys\fR. Just take the file \fIdef/sample.xml\fR or an
existing definition file as an example.
.SH "CONFIGURATION FILE"
The configuration file is named \fIhotkeys.conf\fR. By default it is
installed in the /usr/local/etc directory. You can also put one into
\fI$HOME/.hotkeys/\fR, which will override the settings in the global
file if one exists.  In other words, the order of parsing is the
global file first and then the private one.  The syntax of the file
uses the simple key=value pairs. Blank lines and lines starting with #
are ignored. Valid keys are written in the default file, which should
be self-explanatory.
.SH "NOTES"
Do not disable the XKEYBOARD extension. For XFree86 3.x, make sure
\fBXkbDisable\fR is not set.
.SH "TODO"
Please consult the TODO file.
.SH "BUGS"
.B
Please inform me if some of your normal keys lose functionalities
.B
after running hotkeys.
.PP
APM support is highly experimental. I only tested on my desktop and
sometimes it can't go out from Suspend mode, no response from the
keyboard, mouse, nor the suspend button on the case. Not tested on
notebook (I don't have one). Note that you need root priviledge to use
the APM functions.
.PP
There are probably bugs in the \fIconfigure.in\fR script.
.PP
The error
\fB"X Error of failed request:  BadValue (integer parameter out of range
for operation)"\fR should have been fixed finally in version 0.5.2.
Please report if it spits out this error on your system.
.SH COPYRIGHT
Copyright 2000-2001, Anthony Y P Wong <ypwong@ypwong.org>
.PP
Licensed under GNU GPL version 2 or later.  This  is  free software;
see the source for copying conditions. There is NO warranty; not even
for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHOR
Anthony Y P Wong, Debian GNU/Linux
